const CHAT_IMAGES_FOLDER_NAME = "chat_images";
const CHAT_VIDEOS_FOLDER_NAME = "chat_videos";
const CHAT_AVATAR_IMAGES_FOLDER_NAME = "chat_avatar_images_folder_name";
const GROUP_CHANNEL_AVATAR_FOLDER_NAME = "group_channel_avatar";
const PROFILE_AVATAR_FOLDER_NAME = "profile_avatar";
const STORY_IMAGES_FOLDER_NAME = "story_images";
const STORY_VIDEOS_FOLDER_NAME = "story_videos";
const WALLPAPER_IMAGES_FOLDER_NAME = "wallpaper_images";
const UNTRACKED_FOLDER = "untracked";
const CHATFOLIO_CLOUDINARY_ROOT_FOLDER_NAME = "chatfolio";

export const CloudinaryConstant = {
  CHAT_IMAGES_FOLDER_NAME,
  CHAT_VIDEOS_FOLDER_NAME,
  CHAT_AVATAR_IMAGES_FOLDER_NAME,
  GROUP_CHANNEL_AVATAR_FOLDER_NAME,
  PROFILE_AVATAR_FOLDER_NAME,
  STORY_IMAGES_FOLDER_NAME,
  STORY_VIDEOS_FOLDER_NAME,
  WALLPAPER_IMAGES_FOLDER_NAME,
  UNTRACKED_FOLDER,
  CHATFOLIO_CLOUDINARY_ROOT_FOLDER_NAME,
};
